### *Tensors*

#### Overview

In [46]:
import tensorflow as tf
import numpy as np

x = tf.constant([[1.,2.,3.] , [5.,6.,7.]])

In [31]:
print(x)
print(x.shape)
print(x.dtype)

tf.Tensor(
[[1. 3. 3.]
 [5. 7. 7.]], shape=(2, 3), dtype=float32)
(2, 3)
<dtype: 'float32'>


In [32]:
x+x

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 2.,  6.,  6.],
       [10., 14., 14.]], dtype=float32)>

In [33]:
x*x

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 1.,  9.,  9.],
       [25., 49., 49.]], dtype=float32)>

In [34]:
x @ tf.transpose(x)  # @ is for matrix multiplication

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 19.,  47.],
       [ 47., 123.]], dtype=float32)>

In [35]:
tf.concat([x,x], axis=1)  # axis = 0 is for vertical concatenation and axis = 1 is for horizontal concatenation

<tf.Tensor: shape=(2, 6), dtype=float32, numpy=
array([[1., 3., 3., 1., 3., 3.],
       [5., 7., 7., 5., 7., 7.]], dtype=float32)>

In [41]:
tf.nn.softmax(x,axis = -1)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.09003057, 0.24472848, 0.66524094],
       [0.09003057, 0.24472848, 0.66524094]], dtype=float32)>

In [42]:
tf.reduce_sum(x, axis = 1)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 6., 18.], dtype=float32)>

In [43]:
tf.convert_to_tensor([1,2,4])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 4], dtype=int32)>

In [44]:
tf.reduce_sum([1,2,3])

<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [45]:
if tf.config.list_physical_devices('GPU'):
    print("Tensor flow **IS** using GPU")
else:
    print("Tensor flow **IS NOT** using GPU")

Tensor flow **IS NOT** using GPU


#### Basics

In [47]:
rank_0_tensor = tf.constant(4)

In [48]:
print(rank_0_tensor)

tf.Tensor(4, shape=(), dtype=int32)


In [56]:
rank_1_tensor = tf.constant([1.,2.,3.])

In [57]:
print(rank_1_tensor)

tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)


In [62]:
rank_2_tensor = tf.constant([[1,2],[3,4],[5,6]] , dtype = tf.float16)

In [63]:
print(rank_2_tensor)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)


In [64]:
rank_3_tensor = tf.constant([[[1,2,3] , [4,5,6]],[[7,8,9],[10,11,12]], [[13,14,15],[16,17,18]]])

In [66]:
print(rank_3_tensor)

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]], shape=(3, 2, 3), dtype=int32)


Converting tensor array to numpy array 

In [67]:
# Way 1:
np.array(rank_2_tensor)

array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)

In [68]:
# Way 2: 
rank_2_tensor.numpy()

array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)

In [69]:
a = tf.constant([[1, 2],
                 [3, 4]])
b = tf.constant([[1, 1],
                 [1, 1]]) # Could have also said `tf.ones([2,2], dtype=tf.int32)`

print(tf.add(a, b), "\n")
print(tf.multiply(a, b), "\n")
print(tf.matmul(a, b), "\n")

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32) 



In [70]:
c = tf.constant([[4.0, 5.0], [10.0, 1.0]])

# Find the largest value
print(tf.reduce_max(c))
# Find the index of the largest value
print(tf.math.argmax(c))
# Compute the softmax
print(tf.nn.softmax(c))

tf.Tensor(10.0, shape=(), dtype=float32)
tf.Tensor([1 0], shape=(2,), dtype=int64)
tf.Tensor(
[[2.6894143e-01 7.3105860e-01]
 [9.9987662e-01 1.2339458e-04]], shape=(2, 2), dtype=float32)


#### Shapes

In [76]:
rank_4_tensor = tf.zeros([3, 2, 4, 5])

In [79]:
print("Type of every element:", rank_4_tensor.dtype)
print("Number of axes:", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along the last axis of tensor:", rank_4_tensor.shape[-1])
print("Total number of elements (3*2*4*5): ", tf.size(rank_4_tensor).numpy())

Type of every element: <dtype: 'float32'>
Number of axes: 4
Shape of tensor: (3, 2, 4, 5)
Elements along axis 0 of tensor: 3
Elements along the last axis of tensor: 5
Total number of elements (3*2*4*5):  120


#### Manipulatign Shapes

In [86]:
# Shape returns a `TensorShape` object that shows the size along each axis
y = tf.constant([[1], [2], [3]])
print(y)
print(y.shape)

tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32)
(3, 1)


In [83]:
# You can convert this object into a Python list, too
print(y.shape.as_list())

[3, 1]


In [85]:
# You can reshape a tensor to a new shape.
# Note that you're passing in a list
reshaped = tf.reshape(y, [1, 3])
print(reshaped)

tf.Tensor([[1 2 3]], shape=(1, 3), dtype=int32)


In [ ]:
print(y.shape)
print(reshaped.shape)